### PR TITLE
Upgraded webpack-config to support Webpack v4

### PR DESCRIPTION
**Pull request by nzapponi**
@elsigh here is the upgraded Webpack config to support v4 and the latest updates.
I replaced a bunch of plugins and rewrote parts of webpack.config.js to support the newer version.
I also modified the config to minify CSS too, reducing the file size in production builds (approx. 20% smaller).

Overall, Uglify does a better job as well, making the js bundle smaller.
In total, I noticed a reduction in the overall app.ele bundle file size of approx 15-25%.

Side effects of this update are also the fixing of issue #30 and the clearing of all vulnerabilities that npm used to identify on Quip Live Apps.

I have tested it on three live apps and it worked fine, could you test it out as well?
Thanks!

### CODE REVIEW

**Comment by nzapponi** [comment]
Any updates on this @elsigh @pedramr ?

**Comment by elsigh** [comment]
@nzapponi rebase? We need to see this through.

**Comment by jesseditson** [comment]
Looping back to this - I'd like to use this as a starting point for modernizing this repo. @nzapponi can you rebase when you get a chance? Alternatively I'll integrate in a separate PR if you're occupied!

**Comment by nzapponi** [comment]
@jesseditson I'd recommend integrating it into another PR and testing the work again before pulling!

**Comment by jesseditson** [comment]
Closed via #44

**Pull request closed without merging**
