### PR TITLE
Change devServer's contentBase

### PR DESCRIPTION
**Pull request by ktzhang**
Make DevServer content base to be app instead of app/dist so that we can expose manifest.json when using local resources.

### CODE REVIEW

**Review by jesseditson — COMMENTED** [review]
Wouldn't this mean that we'd need to import things from `/dist`? Won't that break things?

**Comment by jesseditson** [comment]
It's 100% possible that I don't understand how webpack works in this case.

**Comment by gaspar09** [comment]
> Wouldn't this mean that we'd need to import things from `/dist`? Won't that break things?

@jesseditson , the files specified on the webpack `output` are treated differently. 

On the view-frame we import the bundles specified in the manifest.json. These bundles are served according to the [output publicPath](https://webpack.js.org/configuration/output/#outputpublicpath)

https://github.com/quip/quip/blob/ba826da7da14202945e65c7adb4383b7972d32b2/templates%2Felement%2Fview-frame.html#L15-L35

whereas the devServer contentBase applies to static files not generated from webpack. So all references to the bundles required on PROD should be okay.

**Review by gaspar09 — APPROVED** [review]

**Review by jesseditson — CHANGES_REQUESTED** [review]
What happens when:

- given the folder structure
```
app/
└── dist/
    └── assets/
        └── image.png
```
- a customer points to an asset in dist in their markup, e.g. ``
- in their manifest.json they have also pointed to this file
- they run npm install and pick up this change
- their asset no longer works locally (it is now served at `image.png`)

Isn't that valid? I think we should at minimum bump minor unless I'm not missing something that would cause hardcoded paths to continue working (or maybe that use case is invalid). I've reproduced this case locally by setting contentBase to `path.resolve(__dirname)`, pointing to an asset in `assets`, then changing the contentBase to `path.resolve("assets")`, which breaks things.

**Comment by ktzhang** [comment]
> Wouldn't this mean that we'd need to import things from `/dist`? Won't that break things?

Yes, @gaspar09 is right.
Just from local testing (where i changed the public path to be "/diste" instead of "/dist", and the content base to be "app":
Screen Shot 2020-12-01 at 10 42 16 AM

Here's the docs:
Screen Shot 2020-12-01 at 10 50 49 AM
So right now with the webpack dev server:
-- app.js will be served in prod at https://localhost:8888/dist 
-- all files will be served statically at https://localhost:8888/
(and since all files includes the directory /dist), the output files will have precedence.

**Comment by jesseditson** [comment]
Right, this works fine for webpack-controlled assets, as the paths will be remapped automatically. But I think this surfaces a (perhaps pre-existing) issue around `other_resources` being potentially located in different places in prod and dev. I think if this is set to anything other than `path.join(__dirname)`, we'll upload the asset to a different place than where webpack is serving it. (since we just use the path in manifest.json, which must be relative to the root for `qla publish` to work)

**Comment by ktzhang** [comment]
> What happens when:
> 
> * given the folder structure
> 
> ```
> app/
> └── dist/
>     └── assets/
>         └── image.png
> ```
> 
> * a customer points to an asset in dist in their markup, e.g. ``
> * in their manifest.json they have also pointed to this file
> * they run npm install and pick up this change
> * their asset no longer works locally (it is now served at `dist/assets/image.png`)
> 
> Isn't that valid? I think we should at minimum bump minor unless I'm not missing something that would cause hardcoded paths to continue working (or maybe that use case is invalid). I've reproduced this case locally by setting contentBase to `path.resolve(__dirname)`, pointing to an asset in `assets`, then changing the contentBase to `path.resolve("assets")`, which breaks things.

Ah Jesse you're right (as usual). This would mess up the paths of static files served from the dist directory. Let me play around to see if there's a way to serve just the manifest.json file statically.

**Comment by jesseditson** [comment]
I honestly would be supportive of:
- bump minor
- change `contentBase` to `path.resolve(__dirname)`
- look for `/manifest.json` and `/app/manifest.json` if it 404s (to support legacy apps)

**Comment by jesseditson** [comment]
@gaspar09 what do you think of this ☝️

**Comment by gaspar09** [comment]
@jesseditson , I had assumed that app/dist was entirely webpack output. 

Doesn't "change contentBase to path.resolve(__dirname)" yield the same issue though?

an asset loaded as `` from app.js in app/dist/app.js will now be located at `https:localhost:8888/app/dist/assets/image.png` rather than `https:localhost:8888/assets/image.png`

**Comment by jesseditson** [comment]
Yeah I'm thinking that if we're going to make a breaking change on this side, may as well give us better compatibility with the new tooling in the process (which is also why I expect we'll need a minor version bump). The alternative in my mind would be to not make changes here and instead make the manifest.json detection work with the paths output by the existing config.

**Comment by gaspar09** [comment]
I think we need to spend some time thinking about the separation of the quip-webpack-config package and the new qla package. Especially if we'd someday like to support a Parcel template.

Leaving the quip-webpack-config package unchanged SGTM. We can also have this be a feature of the new manifest version/ project-structure since It's not too difficult to migrate our first party apps to have manifest.json on the project root

**Comment by jesseditson** [comment]
Yeah I mean technically this package is already effectively deprecated because `create-quip-app` aliases `qla init`, which uses the new template and no longer imports this config.

For posterity:
The manifest.json file should be the "source of truth" when it comes to what is in the bundle. While we cannot prevent people from configuring their dev differently than their prod, the new init template sets them up for success with the default config in that if they point to paths in the manifest.json, the paths will align with where webpack serves static assets by default (the root). This is also unlikely to need to change since it's already serving every file in the app dir.

@ktzhang sounds like we should just make https://github.com/quip/quip/pull/10110 handle the legacy paths (can just try them if the root manifest 404s) and avoid changes here

**Comment by gaspar09** [comment]
Just a side note: looks like this preferred method is to use a loader for most common asset types. 

https://webpack.js.org/guides/asset-management/

in which case the `assets/image.png` should be processed by webpack

**Comment by jesseditson** [comment]
The only issue there is that even though webpack will process the image and put it in `dist`, it won't necessarily be available in production. I think best practice if you want webpack to manage your assets would be to include `dist/assets` under `other_resources`, but I think you may still need to do something special to your config (e.g. set file-loader's outputPath to `dist/assets`, and perhaps change the contentBase) to make sure that `dist` is present in the dev-server paths, otherwise your prod will still be broken. In summary, if you want to include static assets:

- Webpack's `devServer.contentBase` needs to be the directory containing `manifest.json`
- Webpack's `output.path` should be a child directory
- All assets generated by Webpack loaders need to be included in `other_resources` or they will not be present in prod.

For instance, I think we can wildcard the `outputPath` of `file-loader` to get prod assets.

**Comment by XinchenApril** [comment]
This is not relevant to this PR but I was testing out how webpack works and I found out if we do `path.resolve(cwd, "app/dist")` then we can access app.js by https://localhost:8888/dist/app.js or https://localhost:8888/app.js
however if we do `path.resolve(cwd, "app")` wen can't access via https://localhost:8888/dist/app.js but via https://localhost:8888/app.js. why is that? Can someone help me understand it?

**Comment by jesseditson** [comment]
@XinchenApril that doesn't sound correct, I'm wondering if maybe your local has both present - what happens if you `rm -rf app/dist` first? (The theory would be that at some point a `dist/dist` folder was created). Or maybe webpack does something special around serving files from the app root?

**Comment by ktzhang** [comment]
> This is not relevant to this PR but I was testing out how webpack works and I found out if we do `path.resolve(cwd, "app/dist")` then we can access app.js by https://localhost:8888/dist/app.js or https://localhost:8888/app.js
> however if we do `path.resolve(cwd, "app")` wen can't access via https://localhost:8888/dist/app.js but via https://localhost:8888/app.js. why is that? Can someone help me understand it?

Did you change path.resolve(cwd, "app/dist") for devServer->contentBase?

**Comment by jesseditson** [comment]
Closing this out since I think we've addressed. Feel free to rebase/reopen if that's not right!

**Pull request closed without merging**
