### PR TITLE
Updated public quip-apps repo nomenclature

### PR DESCRIPTION
**Pull request by nzapponi**
- Renamed Quip Apps to Quip Live Apps
- Reviewed and updated `quip-cli` readme

### CODE REVIEW

**Comment by nzapponi** [comment]
@gaspar09

**Comment by nzapponi** [comment]
@abbyomotoso

**Comment by abbyomotoso** [comment]
Thanks @nzapponi . I have a few minor comments. I can get back to you by the end of this week.

**Comment by gaspar09** [comment]
@nzapponi , i believe the quip-cli readme can also be autogenerated. e.g. the command descriptions are filled using the description on the individual command file. https://github.com/quip/quip-apps/blob/83291cd9ec680f726a750c806c07284147c506f4/packages/quip-cli/src/commands/release.ts#L83

**Review by abbyomotoso — CHANGES_REQUESTED** [review]
Hi @nzapponi . I suggest the changes highlighted in yellow in this doc:
https://corp.quip.com/UPaVAZH9szri/Wording-for-Readme-Doc-in-Live-Apps-GitHub-Repo

**Comment by nzapponi** [comment]
Ok sounds good, I'll update those instead. Leave the PR open for now!

**Comment by nzapponi** [comment]
@gaspar09 here it is, I autogenerated the readme based on oclif!
I also made the following changes:
- I updated dependencies on the package as there were a bunch of medium and high vulnerabilities. LGTM, but we probably need to test it before merging
- I renamed the package to quip-cli rather than qla, I feel like it's more consistent with the rest of the platform. LMK what you think

> Hi @nzapponi . I suggest the changes highlighted in yellow in this doc:
> https://corp.quip.com/UPaVAZH9szri/Wording-for-Readme-Doc-in-Live-Apps-GitHub-Repo

@abbyomotoso , I thought we had decided that that content would be on a separate page on quip.com/dev/ , rather than on GitHub, right?
Let me know what you think and if you'd like to mirror the content in both places.

Thanks!

**Comment by abbyomotoso** [comment]
@nzapponi . My understanding based on what we discussed in our meeting with Gaspar ([see notes in yellow here](https://corp.quip.com/dFiYA5qarEcd/Anywhere-Dev-Doc-Projects#XFLACAmCL2Y)) is that we would:

- Create a separate page for the Quip CLI guide ([as you've done in this draft](https://corp.quip.com/4aY4AiO8HNdy#BBGABAtkhfN)) and include a link to the Quip CLI GitHub repo.
- Tweak the wording in the readme file for the Live Apps GitHub repo and not have a separate page for it on quip.com/dev.

I think that makes sense since GitHub repos typically have readme files and tools/apps (such as CLIs) may have guides and/or UI text as needed.

**Comment by nzapponi** [comment]
Hi @abbyomotoso ,
Thanks! Yes, sorry, I got confused between the readme of the overall repo vs the quip cli folder within the repo.
Got it, I'll add your updated text to this PR

**Comment by nzapponi** [comment]
Done, you can see the preview here @abbyomotoso : https://github.com/nzapponi/quip-apps

**Review by abbyomotoso — APPROVED** [review]
LGTM. Thanks!

**Review by gaspar09 — APPROVED** [review]

**Comment by nzapponi** [comment]
@FlikHu would you be able to merge this one please?

**Pull request merged**
